import { Injectable, signal, computed } from '@angular/core';
import { MangaSource } from '../models/source.model';
import { getAllAdapterIds } from './source-adapters';

const AVAILABLE_SOURCES: MangaSource[] = [
  // ─── Multi-language ───────────────────────────────────────────────────────────
  {
    id: 'mangadex',
    name: 'MangaDex',
    lang: 'Multi',
    version: '2.0',
    icon: 'MD',
    iconColor: '#ff6740',
    baseUrl: 'https://mangadex.org',
    description: 'The largest manga source. No ads, multi-language.',
    descriptionEs: 'La fuente de manga más grande. Sin anuncios, multi-idioma.',
    features: ['Multi-idioma', 'Sin auth', 'Capítulos gratis'],
    nsfw: false,
  },
  {
    id: 'comick',
    name: 'ComicK',
    lang: 'Multi',
    version: '1.5',
    icon: 'CK',
    iconColor: '#5c6bc0',
    baseUrl: 'https://comick.io',
    description: 'Fast aggregator. No ads, clean interface.',
    descriptionEs: 'Agregador rápido. Sin anuncios, interfaz limpia.',
    features: ['Rápido', 'Sin anuncios', 'Multi-idioma'],
    nsfw: false,
  },
  {
    id: 'kitsu',
    name: 'Kitsu',
    lang: 'Multi',
    version: '1.0',
    icon: 'KT',
    iconColor: '#fd8320',
    baseUrl: 'https://kitsu.io',
    description: 'Anime/manga tracking and discovery platform. Community-driven.',
    descriptionEs: 'Plataforma de seguimiento y descubrimiento de anime/manga. Comunidad.',
    features: ['Tracking', 'Comunidad', 'Multi-idioma'],
    nsfw: false,
  },
  {
    id: 'anilist',
    name: 'AniList',
    lang: 'Multi',
    version: '1.0',
    icon: 'AL',
    iconColor: '#02a9ff',
    baseUrl: 'https://anilist.co',
    description: 'Modern anime/manga tracking with rich metadata and community.',
    descriptionEs: 'Seguimiento moderno de anime/manga con metadatos y comunidad.',
    features: ['Tracking', 'Metadatos', 'GraphQL API'],
    nsfw: false,
  },
  {
    id: 'mangaupdates',
    name: 'MangaUpdates',
    lang: 'Multi',
    version: '1.0',
    icon: 'MU',
    iconColor: '#f57c00',
    baseUrl: 'https://www.mangaupdates.com',
    description: 'Comprehensive manga database with ratings and release tracking.',
    descriptionEs: 'Base de datos de manga completa con ratings y seguimiento de lanzamientos.',
    features: ['Base de datos', 'Ratings', 'Releases'],
    nsfw: false,
  },
  {
    id: 'batoto',
    name: 'Bato.to',
    lang: 'Multi',
    version: '2.1',
    icon: 'BT',
    iconColor: '#1b5e20',
    baseUrl: 'https://bato.to',
    description: 'Community-driven manga aggregator. Multi-language uploads.',
    descriptionEs: 'Agregador de manga de la comunidad. Subidas multi-idioma.',
    features: ['Comunidad', 'Multi-idioma', 'Subidas rápidas'],
    nsfw: false,
  },

  // ─── English ──────────────────────────────────────────────────────────────────
  {
    id: 'mangaplus',
    name: 'MangaPlus by Shueisha',
    lang: 'EN',
    version: '1.8',
    icon: 'M+',
    iconColor: '#e91e63',
    baseUrl: 'https://mangaplus.shueisha.co.jp',
    description: 'Official Shueisha source. Free simultaneous releases.',
    descriptionEs: 'Fuente oficial de Shueisha. Lanzamientos simultáneos gratis.',
    features: ['Oficial', 'Simulcast', 'Gratis'],
    nsfw: false,
  },
  {
    id: 'mangasee',
    name: 'MangaSee',
    lang: 'EN',
    version: '1.4',
    icon: 'MS',
    iconColor: '#00897b',
    baseUrl: 'https://mangasee123.com',
    description: 'High quality scans. Fast updates, large library.',
    descriptionEs: 'Scans de alta calidad. Actualizaciones rápidas, gran catálogo.',
    features: ['Alta calidad', 'Catálogo grande', 'Rápido'],
    nsfw: false,
  },
  {
    id: 'mangalife',
    name: 'MangaLife',
    lang: 'EN',
    version: '1.3',
    icon: 'ML',
    iconColor: '#43a047',
    baseUrl: 'https://manga4life.com',
    description: 'Sister site of MangaSee. Same quality, different UI.',
    descriptionEs: 'Sitio hermano de MangaSee. Misma calidad, diferente UI.',
    features: ['Alta calidad', 'Sin anuncios', 'Catálogo grande'],
    nsfw: false,
  },
  {
    id: 'mangapill',
    name: 'MangaPill',
    lang: 'EN',
    version: '1.2',
    icon: 'MP',
    iconColor: '#7b1fa2',
    baseUrl: 'https://mangapill.com',
    description: 'Clean reader with large catalogue. Fast loading.',
    descriptionEs: 'Lector limpio con gran catálogo. Carga rápida.',
    features: ['Limpio', 'Rápido', 'Sin registro'],
    nsfw: false,
  },
  {
    id: 'mangabuddy',
    name: 'MangaBuddy',
    lang: 'EN',
    version: '1.1',
    icon: 'MB',
    iconColor: '#f4511e',
    baseUrl: 'https://mangabuddy.com',
    description: 'Free manga reader with daily updates.',
    descriptionEs: 'Lector de manga gratis con actualizaciones diarias.',
    features: ['Gratis', 'Diario', 'Sin registro'],
    nsfw: false,
  },
  {
    id: 'mangakakalot',
    name: 'MangaKakalot',
    lang: 'EN',
    version: '1.6',
    icon: 'MK',
    iconColor: '#ff8f00',
    baseUrl: 'https://mangakakalot.com',
    description: 'Popular aggregator with massive library. Fast updates.',
    descriptionEs: 'Agregador popular con catálogo masivo. Actualizaciones rápidas.',
    features: ['Masivo', 'Popular', 'Rápido'],
    nsfw: false,
  },
  {
    id: 'manganato',
    name: 'Manganato',
    lang: 'EN',
    version: '1.7',
    icon: 'MN',
    iconColor: '#ff6d00',
    baseUrl: 'https://manganato.com',
    description: 'Successor to MangaKakalot. Clean interface, large library.',
    descriptionEs: 'Sucesor de MangaKakalot. Interfaz limpia, gran catálogo.',
    features: ['Gran catálogo', 'Limpio', 'Popular'],
    nsfw: false,
  },
  {
    id: 'chapmanganato',
    name: 'Chapmanganato',
    lang: 'EN',
    version: '1.2',
    icon: 'CM',
    iconColor: '#e65100',
    baseUrl: 'https://chapmanganato.to',
    description: 'Mirror of Manganato with alternative domain.',
    descriptionEs: 'Mirror de Manganato con dominio alternativo.',
    features: ['Mirror', 'Rápido', 'Sin registro'],
    nsfw: false,
  },
  {
    id: 'asurascans',
    name: 'Asura Scans',
    lang: 'EN',
    version: '2.3',
    icon: 'AS',
    iconColor: '#9c27b0',
    baseUrl: 'https://asuracomic.net',
    description: 'Top manhwa/manhua scanlation group. Fast releases.',
    descriptionEs: 'Grupo top de scanlation manhwa/manhua. Lanzamientos rápidos.',
    features: ['Manhwa', 'Rápido', 'Calidad'],
    nsfw: false,
  },
  {
    id: 'flamescans',
    name: 'Flame Comics',
    lang: 'EN',
    version: '2.0',
    icon: 'FL',
    iconColor: '#ff5252',
    baseUrl: 'https://flamecomics.xyz',
    description: 'Popular scanlation group. Manhwa and manhua focus.',
    descriptionEs: 'Grupo popular de scanlation. Enfoque en manhwa y manhua.',
    features: ['Manhwa', 'Manhua', 'Popular'],
    nsfw: false,
  },
  {
    id: 'reaperscans',
    name: 'Reaper Scans',
    lang: 'EN',
    version: '1.9',
    icon: 'RS',
    iconColor: '#212121',
    baseUrl: 'https://reaperscans.com',
    description: 'Quality scanlation group. Manhwa specialization.',
    descriptionEs: 'Grupo de scanlation de calidad. Especialización en manhwa.',
    features: ['Manhwa', 'Calidad', 'Comunidad'],
    nsfw: false,
  },
  {
    id: 'luminousscans',
    name: 'Luminous Scans',
    lang: 'EN',
    version: '1.5',
    icon: 'LS',
    iconColor: '#ffd600',
    baseUrl: 'https://luminousscans.gg',
    description: 'Fast manhwa scanlations. Daily chapter updates.',
    descriptionEs: 'Scanlations rápidas de manhwa. Capítulos diarios.',
    features: ['Manhwa', 'Diario', 'Rápido'],
    nsfw: false,
  },
  {
    id: 'manhwaclan',
    name: 'Manhwa Clan',
    lang: 'EN',
    version: '1.3',
    icon: 'MC',
    iconColor: '#00bcd4',
    baseUrl: 'https://manhwaclan.com',
    description: 'Manhwa and webtoon aggregator. Large collection.',
    descriptionEs: 'Agregador de manhwa y webtoon. Gran colección.',
    features: ['Manhwa', 'Webtoon', 'Colección grande'],
    nsfw: false,
  },
  {
    id: 'webtoons',
    name: 'Webtoons',
    lang: 'EN',
    version: '2.5',
    icon: 'WT',
    iconColor: '#00c853',
    baseUrl: 'https://www.webtoons.com',
    description: 'Official webtoon platform by Naver/LINE. Free originals.',
    descriptionEs: 'Plataforma oficial de webtoons por Naver/LINE. Originales gratis.',
    features: ['Oficial', 'Originales', 'Gratis'],
    nsfw: false,
  },
  {
    id: 'toonily',
    name: 'Toonily',
    lang: 'EN',
    version: '1.4',
    icon: 'TN',
    iconColor: '#ec407a',
    baseUrl: 'https://toonily.com',
    description: 'Manhwa reader focused on mature content.',
    descriptionEs: 'Lector de manhwa enfocado en contenido maduro.',
    features: ['Manhwa', 'Adulto', 'Actualizado'],
    nsfw: true,
  },
  {
    id: 'readmanhwa',
    name: 'ReadManhwa',
    lang: 'EN',
    version: '1.2',
    icon: 'RM',
    iconColor: '#ad1457',
    baseUrl: 'https://readmanhwa.io',
    description: 'Adult manhwa reader. 18+ content.',
    descriptionEs: 'Lector de manhwa adulto. Contenido +18.',
    features: ['Adulto', '+18', 'Manhwa'],
    nsfw: true,
  },
  {
    id: 'mangafire',
    name: 'MangaFire',
    lang: 'EN',
    version: '1.6',
    icon: 'MF',
    iconColor: '#bf360c',
    baseUrl: 'https://mangafire.to',
    description: 'Modern manga reader. Clean UI, fast loading.',
    descriptionEs: 'Lector de manga moderno. UI limpia, carga rápida.',
    features: ['Moderno', 'Limpio', 'Rápido'],
    nsfw: false,
  },
  {
    id: 'mangareader',
    name: 'MangaReader',
    lang: 'EN',
    version: '1.3',
    icon: 'MR',
    iconColor: '#1565c0',
    baseUrl: 'https://mangareader.to',
    description: 'Feature-rich manga reader. Multiple reading modes.',
    descriptionEs: 'Lector de manga con muchas funciones. Múltiples modos de lectura.',
    features: ['Modos de lectura', 'Funcional', 'Gratis'],
    nsfw: false,
  },
  {
    id: '1stkissmanga',
    name: '1st Kiss Manga',
    lang: 'EN',
    version: '1.1',
    icon: '1K',
    iconColor: '#d81b60',
    baseUrl: 'https://1stkissmanga.me',
    description: 'Romance manhwa and manga. Shoujo/Josei focus.',
    descriptionEs: 'Manhwa y manga romance. Enfoque Shoujo/Josei.',
    features: ['Romance', 'Shoujo', 'Manhwa'],
    nsfw: false,
  },

  // ─── Spanish ──────────────────────────────────────────────────────────────────
  {
    id: 'tumangaonline',
    name: 'TuMangaOnline',
    lang: 'ES',
    version: '2.8',
    icon: 'TM',
    iconColor: '#1976d2',
    baseUrl: 'https://visortmo.com',
    description: 'Largest Spanish manga community. Huge library.',
    descriptionEs: 'La mayor comunidad de manga en español. Catálogo enorme.',
    features: ['Español', 'Comunidad', 'Masivo'],
    nsfw: false,
  },
  {
    id: 'leermanga',
    name: 'LeerManga',
    lang: 'ES',
    version: '1.4',
    icon: 'LM',
    iconColor: '#388e3c',
    baseUrl: 'https://leermanga.net',
    description: 'Spanish manga reader. Daily updates.',
    descriptionEs: 'Lector de manga en español. Actualizaciones diarias.',
    features: ['Español', 'Diario', 'Gratis'],
    nsfw: false,
  },
  {
    id: 'inmanga',
    name: 'InManga',
    lang: 'ES',
    version: '1.2',
    icon: 'IM',
    iconColor: '#00695c',
    baseUrl: 'https://inmanga.com',
    description: 'Spanish manga reading site. Clean interface.',
    descriptionEs: 'Sitio de lectura de manga en español. Interfaz limpia.',
    features: ['Español', 'Limpio', 'Sin registro'],
    nsfw: false,
  },
  {
    id: 'lectormanga',
    name: 'LectorManga',
    lang: 'ES',
    version: '1.6',
    icon: 'LC',
    iconColor: '#283593',
    baseUrl: 'https://lectormanga.com',
    description: 'Popular Spanish manga reader with active community.',
    descriptionEs: 'Lector de manga en español popular con comunidad activa.',
    features: ['Español', 'Comunidad', 'Popular'],
    nsfw: false,
  },
  {
    id: 'mangaenlinea',
    name: 'MangaEnLinea',
    lang: 'ES',
    version: '1.1',
    icon: 'ME',
    iconColor: '#4527a0',
    baseUrl: 'https://mangaenlinea.com',
    description: 'Free manga reading in Spanish. No registration.',
    descriptionEs: 'Lectura de manga gratis en español. Sin registro.',
    features: ['Español', 'Gratis', 'Sin registro'],
    nsfw: false,
  },
  {
    id: 'olympusscans',
    name: 'Olympus Scans',
    lang: 'ES',
    version: '1.7',
    icon: 'OL',
    iconColor: '#6a1b9a',
    baseUrl: 'https://olympusscans.com',
    description: 'Spanish scanlation group. Manhwa and manga translations.',
    descriptionEs: 'Grupo de scanlation en español. Traducciones de manhwa y manga.',
    features: ['Español', 'Scanlation', 'Manhwa'],
    nsfw: false,
  },
  {
    id: 'manhwasnet',
    name: 'Manhwas.net',
    lang: 'ES',
    version: '1.3',
    icon: 'MW',
    iconColor: '#c62828',
    baseUrl: 'https://manhwas.net',
    description: 'Spanish manhwa site. Translated Korean webtoons.',
    descriptionEs: 'Sitio de manhwa en español. Webtoons coreanos traducidos.',
    features: ['Español', 'Manhwa', 'Webtoon'],
    nsfw: false,
  },

  // ─── Japanese ─────────────────────────────────────────────────────────────────
  {
    id: 'rawkuma',
    name: 'Raw Kuma',
    lang: 'JP',
    version: '1.5',
    icon: 'RK',
    iconColor: '#d32f2f',
    baseUrl: 'https://rawkuma.com',
    description: 'Japanese raw manga. Latest releases from Japan.',
    descriptionEs: 'Manga raw japonés. Últimos lanzamientos de Japón.',
    features: ['Raw', 'Japonés', 'Últimos'],
    nsfw: false,
  },
  {
    id: 'mangaraw',
    name: 'Manga Raw',
    lang: 'JP',
    version: '1.3',
    icon: 'RW',
    iconColor: '#b71c1c',
    baseUrl: 'https://manga1001.in',
    description: 'Raw manga in Japanese. Large collection.',
    descriptionEs: 'Manga raw en japonés. Gran colección.',
    features: ['Raw', 'Japonés', 'Colección'],
    nsfw: false,
  },
  {
    id: 'senmangaraw',
    name: 'Sen Manga Raw',
    lang: 'JP',
    version: '1.2',
    icon: 'SM',
    iconColor: '#880e4f',
    baseUrl: 'https://raw.senmanga.com',
    description: 'High quality Japanese raw manga scans.',
    descriptionEs: 'Scans raw de manga japonés en alta calidad.',
    features: ['Raw', 'Alta calidad', 'Japonés'],
    nsfw: false,
  },
  {
    id: 'syosetu',
    name: 'Syosetu',
    lang: 'JP',
    version: '1.0',
    icon: 'SY',
    iconColor: '#4e342e',
    baseUrl: 'https://ncode.syosetu.com',
    description: 'Japanese web novel platform. Light novel source.',
    descriptionEs: 'Plataforma de novelas web japonesas. Fuente de light novels.',
    features: ['Novelas', 'Japonés', 'Light Novels'],
    nsfw: false,
  },

  // ─── Korean ───────────────────────────────────────────────────────────────────
  {
    id: 'manhwa18',
    name: 'Manhwa18.net',
    lang: 'KO',
    version: '1.4',
    icon: '18',
    iconColor: '#6d4c41',
    baseUrl: 'https://manhwa18.net',
    description: 'Korean adult manhwa. 18+ content only.',
    descriptionEs: 'Manhwa adulto coreano. Solo contenido +18.',
    features: ['Adulto', '+18', 'Coreano'],
    nsfw: true,
  },
  {
    id: 'manhwaraw',
    name: 'Manhwa Raw',
    lang: 'KO',
    version: '1.3',
    icon: 'MH',
    iconColor: '#37474f',
    baseUrl: 'https://manhwaraw.com',
    description: 'Raw Korean manhwa. Latest webtoon chapters.',
    descriptionEs: 'Manhwa raw coreano. Últimos capítulos de webtoons.',
    features: ['Raw', 'Coreano', 'Webtoon'],
    nsfw: false,
  },
  {
    id: 'newtoki',
    name: 'NewToki',
    lang: 'KO',
    version: '2.1',
    icon: 'NT',
    iconColor: '#0d47a1',
    baseUrl: 'https://newtoki.com',
    description: 'Popular Korean manga/manhwa aggregator.',
    descriptionEs: 'Agregador popular de manga/manhwa coreano.',
    features: ['Coreano', 'Popular', 'Actualizado'],
    nsfw: false,
  },
  {
    id: 'manatoki',
    name: 'Manatoki',
    lang: 'KO',
    version: '2.0',
    icon: 'MT',
    iconColor: '#1a237e',
    baseUrl: 'https://manatoki.net',
    description: 'Korean manga community. Translated and raw content.',
    descriptionEs: 'Comunidad de manga coreana. Contenido traducido y raw.',
    features: ['Coreano', 'Comunidad', 'Traducido'],
    nsfw: false,
  },

  // ─── Chinese ──────────────────────────────────────────────────────────────────
  {
    id: 'manhuaplus',
    name: 'Manhua Plus',
    lang: 'ZH',
    version: '1.5',
    icon: 'MH',
    iconColor: '#f9a825',
    baseUrl: 'https://manhuaplus.com',
    description: 'Chinese manhua reader. Translated to English.',
    descriptionEs: 'Lector de manhua chino. Traducido al inglés.',
    features: ['Manhua', 'Traducido', 'Gratis'],
    nsfw: false,
  },
  {
    id: 'manhuaes',
    name: 'Manhua ES',
    lang: 'ZH',
    version: '1.2',
    icon: 'MX',
    iconColor: '#ef6c00',
    baseUrl: 'https://manhuaes.com',
    description: 'Chinese manhua translated to Spanish.',
    descriptionEs: 'Manhua chino traducido al español.',
    features: ['Manhua', 'Español', 'Chino'],
    nsfw: false,
  },

  // ─── French ───────────────────────────────────────────────────────────────────
  {
    id: 'mangascan',
    name: 'Manga Scan',
    lang: 'FR',
    version: '1.4',
    icon: 'SC',
    iconColor: '#0277bd',
    baseUrl: 'https://mangascan.cc',
    description: 'French manga scanlation site. Active community.',
    descriptionEs: 'Sitio de scanlation de manga francés. Comunidad activa.',
    features: ['Francés', 'Scanlation', 'Comunidad'],
    nsfw: false,
  },
  {
    id: 'japscan',
    name: 'Japscan',
    lang: 'FR',
    version: '2.2',
    icon: 'JS',
    iconColor: '#01579b',
    baseUrl: 'https://www.japscan.lol',
    description: 'Largest French manga reader. Huge catalogue.',
    descriptionEs: 'El mayor lector de manga francés. Catálogo enorme.',
    features: ['Francés', 'Masivo', 'Popular'],
    nsfw: false,
  },
  {
    id: 'scanmanga',
    name: 'Scan-Manga',
    lang: 'FR',
    version: '1.3',
    icon: 'SF',
    iconColor: '#4fc3f7',
    baseUrl: 'https://scan-manga.com',
    description: 'French manga scans. Fast updates.',
    descriptionEs: 'Scans de manga en francés. Actualizaciones rápidas.',
    features: ['Francés', 'Rápido', 'Gratis'],
    nsfw: false,
  },

  // ─── Portuguese ───────────────────────────────────────────────────────────────
  {
    id: 'mangalivre',
    name: 'Manga Livre',
    lang: 'PT',
    version: '2.4',
    icon: 'LV',
    iconColor: '#2e7d32',
    baseUrl: 'https://mangalivre.net',
    description: 'Largest Portuguese manga source. Active community.',
    descriptionEs: 'La mayor fuente de manga en portugués. Comunidad activa.',
    features: ['Portugués', 'Masivo', 'Comunidad'],
    nsfw: false,
  },
  {
    id: 'unionmangas',
    name: 'Union Mangas',
    lang: 'PT',
    version: '1.6',
    icon: 'UM',
    iconColor: '#558b2f',
    baseUrl: 'https://unionmangas.top',
    description: 'Brazilian Portuguese manga reader. Large library.',
    descriptionEs: 'Lector de manga en portugués brasileño. Gran catálogo.',
    features: ['Portugués', 'Brasil', 'Gran catálogo'],
    nsfw: false,
  },
  {
    id: 'supermangas',
    name: 'Super Mangas',
    lang: 'PT',
    version: '1.2',
    icon: 'SP',
    iconColor: '#33691e',
    baseUrl: 'https://supermangas.site',
    description: 'Free Portuguese manga reading. No registration.',
    descriptionEs: 'Lectura de manga en portugués gratis. Sin registro.',
    features: ['Portugués', 'Gratis', 'Sin registro'],
    nsfw: false,
  },

  // ─── Indonesian ───────────────────────────────────────────────────────────────
  {
    id: 'komikindo',
    name: 'Komik Indo',
    lang: 'ID',
    version: '1.5',
    icon: 'KI',
    iconColor: '#e53935',
    baseUrl: 'https://komikindo.co',
    description: 'Indonesian manga/manhwa reader. Large collection.',
    descriptionEs: 'Lector de manga/manhwa indonesio. Gran colección.',
    features: ['Indonesio', 'Manhwa', 'Gran colección'],
    nsfw: false,
  },
  {
    id: 'maidmanga',
    name: 'Maid Manga',
    lang: 'ID',
    version: '1.3',
    icon: 'MM',
    iconColor: '#f06292',
    baseUrl: 'https://www.mfraws.com',
    description: 'Indonesian manga translations. Daily updates.',
    descriptionEs: 'Traducciones de manga indonesio. Actualizaciones diarias.',
    features: ['Indonesio', 'Diario', 'Traducido'],
    nsfw: false,
  },
];

@Injectable({ providedIn: 'root' })
export class SourceRegistryService {
  private readonly STORAGE_KEY = 'installed_sources';
  private readonly DEFAULT_SOURCES = ['mangadex'];

  private readonly installedIds = signal<string[]>(this.loadInstalled());

  readonly available = signal<MangaSource[]>(AVAILABLE_SOURCES);

  readonly installed = computed(() => {
    const ids = this.installedIds();
    return AVAILABLE_SOURCES.filter(s => ids.includes(s.id));
  });

  readonly notInstalled = computed(() => {
    const ids = this.installedIds();
    return AVAILABLE_SOURCES.filter(s => !ids.includes(s.id));
  });

  isInstalled(sourceId: string): boolean {
    return this.installedIds().includes(sourceId);
  }

  hasAdapter(sourceId: string): boolean {
    return getAllAdapterIds().includes(sourceId);
  }

  install(sourceId: string): void {
    const current = this.installedIds();
    if (current.includes(sourceId)) return;
    const updated = [...current, sourceId];
    this.installedIds.set(updated);
    this.saveToStorage(updated);
  }

  uninstall(sourceId: string): void {
    const current = this.installedIds();
    const updated = current.filter(id => id !== sourceId);
    this.installedIds.set(updated);
    this.saveToStorage(updated);
  }

  getAvailable(): MangaSource[] {
    return AVAILABLE_SOURCES;
  }

  getInstalled(): MangaSource[] {
    return this.installed();
  }

  private loadInstalled(): string[] {
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch {
      // ignore parse errors
    }
    // Default: MangaDex is installed
    this.saveToStorage(this.DEFAULT_SOURCES);
    return [...this.DEFAULT_SOURCES];
  }

  private saveToStorage(ids: string[]): void {
    localStorage.setItem(this.STORAGE_KEY, JSON.stringify(ids));
  }
}
